version: "3.9"

services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: ihsan-postgres

    restart: unless-stopped

    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ihsan_raq_ai

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: