"""create document units table

Revision ID: 9355ca565284
Revises: 460b590793a9
Create Date: 2026-08-01 14:38:21.971769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9355ca565284'
down_revision: Union[str, Sequence[str], None] = '460b590793a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_units',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('unit_index', sa.Integer(), nullable=False),
    sa.Column('unit_type', sa.String(length=20), nullable=False),
    sa.Column('source_label', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('char_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('unit_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("unit_type IN ('page', 'slide', 'sheet', 'section', 'text')", name='ck_document_units_type'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'unit_index', name='uq_document_units_document_index')
    )
    op.create_index(op.f('ix_document_units_content_hash'), 'document_units', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_units_document_id'), 'document_units', ['document_id'], unique=False)
    op.create_index('ix_document_units_document_type', 'document_units', ['document_id', 'unit_type'], unique=False)
    op.create_index(op.f('ix_document_units_unit_type'), 'document_units', ['unit_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_units_unit_type'), table_name='document_units')
    op.drop_index('ix_document_units_document_type', table_name='document_units')
    op.drop_index(op.f('ix_document_units_document_id'), table_name='document_units')
    op.drop_index(op.f('ix_document_units_content_hash'), table_name='document_units')
    op.drop_table('document_units')
    # ### end Alembic commands ###
