"""create advanced document chunks table

Revision ID: b3cae84f1c71
Revises: efccc086aeb7
Create Date: 2026-08-03 01:46:56.217096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b3cae84f1c71'
down_revision: Union[str, Sequence[str], None] = 'efccc086aeb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('document_id', sa.String(), nullable=False),
    sa.Column('document_unit_id', sa.String(), nullable=True),
    sa.Column('parent_chunk_id', sa.String(), nullable=True),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_level', sa.Integer(), server_default='0', nullable=False),
    sa.Column('chunk_role', sa.String(length=20), server_default='content', nullable=False),
    sa.Column('source_label', sa.String(length=255), nullable=False),
    sa.Column('section_path', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding_content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('token_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('char_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('word_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.Column('start_page', sa.Integer(), nullable=True),
    sa.Column('end_page', sa.Integer(), nullable=True),
    sa.Column('strategy_version', sa.String(length=50), server_default='iahc-x-v1', nullable=False),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("chunk_role IN ('content', 'summary', 'proposition')", name='ck_document_chunks_role'),
    sa.CheckConstraint('(start_char IS NULL AND end_char IS NULL) OR (start_char >= 0 AND end_char >= start_char)', name='ck_document_chunks_character_range'),
    sa.CheckConstraint('(start_page IS NULL AND end_page IS NULL) OR (start_page >= 1 AND end_page >= start_page)', name='ck_document_chunks_page_range'),
    sa.CheckConstraint('chunk_level >= 0', name='ck_document_chunks_level'),
    sa.CheckConstraint('token_count >= 0 AND char_count >= 0 AND word_count >= 0', name='ck_document_chunks_counts'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['document_unit_id'], ['document_units.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['document_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'strategy_version', 'chunk_index', name='uq_document_chunks_strategy_index')
    )
    op.create_index(op.f('ix_document_chunks_chunk_role'), 'document_chunks', ['chunk_role'], unique=False)
    op.create_index(op.f('ix_document_chunks_content_hash'), 'document_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_document_chunks_document_id'), 'document_chunks', ['document_id'], unique=False)
    op.create_index('ix_document_chunks_document_strategy_role', 'document_chunks', ['document_id', 'strategy_version', 'chunk_role'], unique=False)
    op.create_index('ix_document_chunks_document_unit', 'document_chunks', ['document_id', 'document_unit_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_parent_chunk_id'), 'document_chunks', ['parent_chunk_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_chunks_parent_chunk_id'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_document_unit', table_name='document_chunks')
    op.drop_index('ix_document_chunks_document_strategy_role', table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_document_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_content_hash'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_chunk_role'), table_name='document_chunks')
    op.drop_table('document_chunks')
    # ### end Alembic commands ###
