"""enforce unique document checksums per user

Revision ID: efccc086aeb7
Revises: 9355ca565284
Create Date: 2026-08-03 00:48:07.945384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efccc086aeb7'
down_revision: Union[str, Sequence[str], None] = '9355ca565284'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_user_checksum'), table_name='documents')
    op.create_unique_constraint('uq_documents_user_checksum', 'documents', ['user_id', 'checksum_sha256'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_documents_user_checksum', 'documents', type_='unique')
    op.create_index(op.f('ix_documents_user_checksum'), 'documents', ['user_id', 'checksum_sha256'], unique=False)
    # ### end Alembic commands ###
